apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking
  namespace: mlflow
  labels:
    app: mlflow-tracking
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 32202
    protocol: TCP
    name: traking
  selector:
    app: mlflow-tracking
