apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pgsql
  namespace: mlflow
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
