apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: https://kf.k3.acornsoft.io/dex
    #issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    connectors:
      - type: gitlab
        id: gitlab
        name: GitLab
        config:
          baseURL: https://git.k3.acornsoft.io
          clientID: 41c718906f52916bdf43e56d13ebc06efcfb899d89a66428f598437b1ae27255
          clientSecret: ee098e235e47823887c32777c04ca383f83d6e3bbb3631cd84ba74b12da9783b
          redirectURI: https://kf.k3.acornsoft.io/dex/callback
          #groups:
          #- open
          useLoginAsID: false
      - type: github
        id: github
        name: Github
        config:
          clientID: 12a6d94647d122abf193
          clientSecret: 2394e3a732fe4d9ecdc5717286937f9b13f26ef5
          redirectURI: https://kf.k3.acornsoft.io/dex/callback
          #groups:
          #- open
          useLoginAsID: false
      - type: google
        id: google
        name: Google
        config:
          clientID: 968321444210-v8sd4e05lhmtdes5livublf2vrd4pr46.apps.googleusercontent.com
          clientSecret: X-u_fioJQ0f3tJL_LdAGuI-Q
          redirectURI: https://kf.k3.acornsoft.io/dex/callback
          #groups:
          #- open
          useLoginAsID: false

    logger:
      level: "debug"
      format: text
    #skipAuthURI:
    #- /dex
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: ohs@acornsoft.io
      hash: $2b$10$GNI/DI.pAHpoADN7dQTKfe8bxb8CA/wYhjmhOF8084aOK4OJrBbiS
      # https://github.com/dexidp/dex/pull/1601/commits
      # FIXME: Use hashFromEnv instead
      username: ohs
      userID: "15841185641785"
    - email: user@kubeflow.org
      hash: $2b$10$dEZK9VowJp9wTW5hU0DTVOztdXj.C7MFBLQKfLym6/0ILqhgHdYi6
      # https://github.com/dexidp/dex/pull/1601/commits
      # FIXME: Use hashFromEnv instead
      username: user
      userID: "15841185641784"
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/login/oidc","https://kf.k3.acornsoft.io/login/oidc","https://kf.k3.acornsoft.io/dex/callback"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
