apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: mlflow
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - name: "4888"
      port: 4888
      nodePort: 32203
      protocol: TCP
      targetPort: 4888