apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- virtual-service.yaml

namespace: istio-system

#commonLabels:
#  kustomize.component: centraldashboard
#  app: centraldashboard
#  app.kubernetes.io/component: centraldashboard
#  app.kubernetes.io/name: centraldashboard

configurations:
- params.yaml
