apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "KZcqfvfZeC1nJ0zVnPFExcjdWkfli3adMuon6lsCoWeus1th61OXGNaYWZ0UGiwY\n9LaxKCYIKPPlKsklqJaCvqx4ngW6VbOS5lxHGlAqWfF1ISzIDqw0yggwUTNi4wWz\nYumg/uuaSu6uy9IN5LOT+jkt0WNdKSkaTjdZ9SwT460="
