apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mlflow-notebook
  name: mlflow-notebook
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-notebook
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: mlflow-notebook
    spec:
      containers:
      - name: mlflow-notebook
        image: regi.k3.acornsoft.io/k3lab/jupyterlab-tf-cpu:3.6-4
        ports:
        - name: dbapi
          containerPort: 8888
        env:
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow-tracking:5000
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /home/jovyan
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mlflow-data
